### PR TITLE
Add sub-regioan diag output example in 1D case

### PR DESCRIPTION
**Pull request by yichengt900**
This PR inclues the following changes:

- enhances the build script to include the `libyaml` build process; 
- added an example diag_table YAML file for sub-region output in the 1D case; 
- added an example xml about how to use new diag manager as well as how to convert legacy `diag_table` to `diag_table.yaml`; 
- added short paragraph for the new yaml style of diag_table in our online documentation. 

Keep in mind the old diag_manager code has been kept intact and will be used by default, so these updates should not have impact to your current experiments. If you want to try the new indices subsetting (comes with the new re-written diag manager), you will have to first build the model system with FMS2 as well as `-Duse_yaml` flag, and set `use_modern_diag = .true.` in your `diag_manager_nml`. You also have to prepare a [yaml format of diag_table](https://github.com/NOAA-GFDL/FMS/blob/main/diag_manager/diag_yaml_format.md).

The sub-region diagnostic works ok with indices for both `NEP` and `Arctic` domains (see below example plot from Arctic domain).  The `NWA` domain works with either latlon or indices subsetting.
example_temp

Also, if you prefer FMS1 and still want to use index subsetting, you can try turning on `USE_INDEX_DIAGNOSTIC_AXES = True` in `MOM6`. This should allow you to specify the `index` instead of `latlon` for sub-region diagnostic output.

### CODE REVIEW

**Comment by theresa-morrison** [comment]
This will be relevant for the NEP and Arctic domains
@wchengpmel @kshedstrom

**Comment by yichengt900** [comment]
Following our discussion this morning, I'd appreciate it if someone could review this PR when there's a chance.

**Comment by kshedstrom** [comment]
My understanding is that the latest FMS is not compatible with the gnu compiler and I therefore can't test this at home. I hope to get to this on gaea next week.

**Comment by yichengt900** [comment]
@kshedstrom, Yes, FMS2 does not work with the latest GCC. It only works with previous versions of GCC.

**Comment by thomas-robinson** [comment]
@kshedstrom do you know which particular version of GCC you are using?

**Comment by kshedstrom** [comment]
gcc (GCC) 11.3.0
I also have access to GCC/12.3.0 
Tests are failing with: FATAL from PE     0: NetCDF: Name contains illegal characters: netcdf_add_variable: file:./ocean_geometry.nc variable:lath

**Comment by yichengt900** [comment]
@uwagura, it would be nice if you could review this PR when you get chance, especially [the new XML file](https://github.com/NOAA-GFDL/CEFI-regional-MOM6/blob/fix/fms2_nudge/xmls/NWA12/CEFI_NWA12_cobalt_fms2_yaml.xml), which is related to the topic of YAML-based diagnostics that @charliestock mentioned. Any comments are more than welcome!

**Comment by kshedstrom** [comment]
Following the NWA xml example, I can compile with yaml and get it to run. However, trying for FMS 2024.01.02 causes it to look for that version of ice_param here:
```
<codeBase version="$(CPL_GIT_TAG)"> ice_param.git </codeBase>
```
and it doesn't find it. I made a separate ICE_PARAM_TAG for it.

Then I got bold and asked for my favorite vertical sections and it failed on me:
```
FATAL from PE  1037: axis_utils2::nearest_index array is NOT monotonously ordered
```
The mess is here: /gpfs/f5/cpo_rmom6/scratch/Katherine.Hedstrom/work/run75_1x1m0d_1648x1o.o135017531

**Comment by kshedstrom** [comment]
My bad - I needed to use USE_INDEX_DIAGNOSTIC_AXES = True. Why did you say it's for FMS1?

**Comment by yichengt900** [comment]
@kshedstrom, thanks for your testing. I fixed the `ice_param` tag issue in the XML.

The `USE_INDEX_DIAGNOSTIC_AXES = True` is a trick from `MOM6`, not `FMS`. The index subsetting comes naturally with the FMS2 newly rewritten diag-manager and should not need to set `USE_INDEX_DIAGNOSTIC_AXES = True`. 

I took a quick look at your config and noticed that the `sub_region` `grid type` in your `diag_table.yaml` is still `latlon`, not `index`. My first guess is this might be an issue from the diag-table-to-yaml [tool](https://github.com/NOAA-GFDL/fre-cli/blob/main/fre/yamltools/diag_table/diag_table_to_yaml.py#L211). Since the legacy `diag_table` does not indicate whether the sub-region is in `latlon` or `index`, the tool probably has a problem identifying that at this moment. @thomas-robinson, can you confirm this is the case?

**Comment by thomas-robinson** [comment]
Tagging @uramirez8707 here just in case he is needed.  The diag table to diag yaml tool translates the diag table, and the diag table only supports _latlon_.  Yes you're correct @yichengt900 . If your diag_table file has a subregion with local indicies and not latlon, then then output produced is probably not what you are expecting,

**Review by uwagura — APPROVED** [review]
Sucessfully completed regression test for layout

**Comment by kshedstrom** [comment]
I recompiled outside of my conda environment and things went rather better (FMS 2024.01.02). Everything is fine as long as I use the old style diag format. Without my small cross-sections, the new format still fails:
```
FATAL from PE    43: freq units is required. Check your entry for file:ocean_hourlyFATAL from PE    43: freq units is required. Check your entry for file:ocean_hourly
```
```
#0  0x31eb527 in __mpp_mod_MOD_mpp_error_basic
        at //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/FMS2/mpp/include/mpp_util_mpi.inc:74
#1  0x3b09506 in parse_key
        at //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/FMS2/diag_manager/fms_diag_yaml.F90:801
#2  0x3b0c140 in fill_in_diag_files
        at //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/FMS2/diag_manager/fms_diag_yaml.F90:551
#3  0x3b119eb in __fms_diag_yaml_mod_MOD_diag_yaml_object_init
        at //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/FMS2/diag_manager/fms_diag_yaml.F90:488
#4  0x3835798 in __fms_diag_object_mod_MOD_fms_diag_object_init
        at //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/FMS2/diag_manager/fms_diag_object.F90:130
#5  0x345fb1b in __diag_manager_mod_MOD_diag_manager_init
        at //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/FMS2/diag_manager/diag_manager.F90:4213
#6  0xfec2ac in coupler_init
        at //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/coupler/full/coupler_main.F90:1566
#7  0xfdb646 in coupler_main
        at //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/coupler/full/coupler_main.F90:590
#8  0xff1607 in main
        at //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/coupler/full/coupler_main.F90:335
```

**Comment by uramirez8707** [comment]
@kshedstrom Can you point me to your diag_table.yaml?

**Comment by kshedstrom** [comment]
I just copied it to /ncrc/home2/Katherine.Hedstrom/ESMG/ESMG-configs/Arctic6/mid_12
on gaea.

**Comment by uramirez8707** [comment]
> /ncrc/home2/Katherine.Hedstrom/ESMG/ESMG-configs/Arctic6/mid_12

@kshedstrom It looks like I don't have permissions to view the file
```
-rw------- 1 Katherine.Hedstrom esrl 10653 Jun 28 13:56 /ncrc/home2/Katherine.Hedstrom/ESMG/ESMG-configs/Arctic6/mid_12/diag_table.yaml
```

**Comment by kshedstrom** [comment]
Oops, sorry, fixed.

**Comment by uramirez8707** [comment]
It looks like your table was generated using an older version of the converter.  Before this update which combined the `freq` and `freq_units` keys: https://github.com/NOAA-GFDL/fms_yaml_tools/pull/26

On gaea, you can do
```
module load fre/bronx-21
diag-table-to-yaml -f /ncrc/home2/Katherine.Hedstrom/ESMG/ESMG-configs/Arctic6/mid_12/diag_table -o diag_table.yaml
```

on your system, please updated your install of fms_yaml_tools.

**Comment by kshedstrom** [comment]
Yes, that works better. Thanks!
The subregion output works for the Bering Sea domain in latlon mode.
I do not have the subregion output working for the Arctic domain in any mode. It seems to accept it in index mode, but doesn't output anything. I assume the tile numbering starts at 0? The attempt in /autofs/ncrc-svm1_home2/Katherine.Hedstrom/ESMG/ESMG-configs/Arctic6/mid_12/diag_table.yaml
is for 24 cores.

**Pull request merged**
